trigger:
  branches:
    include:
      - '*'

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  ci: true
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  repoRoot: $(Build.SourcesDirectory)

jobs:
# - job: Build_project_A
#   steps:
#   - template: .azure/build.yml
#     parameters:
#       projectName: A
#   - template: .azure/publish.yml
#     parameters:
#       projectName: A

- job: Build_project_B
  steps:
  - template: .azure/build.yml
    parameters:
      projectName: B
  - template: .azure/publish.yml
    parameters:
      projectName: B