parameters:
  - name: projectName
    type: string

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 3.1.201'
    inputs:
      packageType: sdk
      version: 3.1.201
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Make sure NuGet is present in directory. This shouldn't be required when pushed to feed.
  - task: DotNetCoreCLI@2
    displayName: Pack NuGet A
    inputs:
      command: pack
      verbosityPack: normal
      arguments: -c $(BuildConfiguration) -p:MinVerSkip=true -p:PackageVersion=1.0.0-alpha
      outputDir: $(artifactsDir)/nuget
      packagesToPack: '**/A.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build project ${{ parameters.projectName }}'
    inputs:
      command: build
      arguments: -c Release
      projects: '**/${{ parameters.projectName }}.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build project ${{ parameters.projectName }}'
    inputs:
      command: build
      arguments: -c Release -t:UpdateBuildNumber -p:MinVerVerbosity=d
      projects: '**/${{ parameters.projectName }}.csproj'
      nobuild: true
