parameters:
  - name: projectName
    type: string

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 3.1.201'
    inputs:
      packageType: sdk
      version: 3.1.201
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: 'Build project ${{ parameters.projectName }}'
    inputs:
      command: build
      arguments: -c Release
      projects: '**/$(parameters.projectName).csproj'
